# pins.tcl - die Pinlagen fuer DIESES Board (RecelFA-Platine mit dem Cyclone 10 Board (10CL006YE144C8G)).
# Wird von scripts\gen_qsf.ps1 in RecelFA.qsf eingesetzt. Handgepflegt.
#
# Das hier ist die Wahrheit ueber die Platine, nicht die Kommentare in der
# VHDL-Portliste. Uebernommen 1:1 aus der alten RecelFA.qsf des flachen
# Projektordners, Reihenfolge unveraendert.

set_location_assignment PIN_66 -to Bonus[1]
set_location_assignment PIN_75 -to Bonus[2]
set_location_assignment PIN_59 -to Bonus[3]
set_location_assignment PIN_23 -to clk_50
set_location_assignment PIN_70 -to Coil[7]
set_location_assignment PIN_72 -to Coil[6]
set_location_assignment PIN_74 -to Coil[5]
set_location_assignment PIN_76 -to Coil[4]
set_location_assignment PIN_77 -to Coil[3]
set_location_assignment PIN_80 -to Coil[2]
set_location_assignment PIN_39 -to Coil[1]
set_location_assignment PIN_86 -to Coil[0]
set_location_assignment PIN_98 -to COIL_Ball_Home
set_location_assignment PIN_99 -to COIL_Knocker
set_location_assignment PIN_43 -to CS_SDcard
set_location_assignment PIN_54 -to Dip_Sw_Ret
set_location_assignment PIN_128 -to Disp_DA[1]
set_location_assignment PIN_132 -to Disp_DA[2]
set_location_assignment PIN_121 -to Disp_DA[3]
set_location_assignment PIN_127 -to Disp_DB[1]
set_location_assignment PIN_124 -to Disp_DB[2]
set_location_assignment PIN_135 -to Disp_DB[3]
set_location_assignment PIN_120 -to Disp_DBS
set_location_assignment PIN_114 -to Disp_Enable
set_location_assignment PIN_138 -to Disp_X[7]
set_location_assignment PIN_136 -to Disp_X[6]
set_location_assignment PIN_141 -to Disp_X[5]
set_location_assignment PIN_133 -to Disp_X[4]
set_location_assignment PIN_142 -to Disp_X[3]
set_location_assignment PIN_137 -to Disp_X[2]
set_location_assignment PIN_143 -to Disp_X[1]
set_location_assignment PIN_129 -to Disp_X[0]
set_location_assignment PIN_2 -to E_DISPLAY_IC_N
set_location_assignment PIN_119 -to E_DRIVER_IC_N
set_location_assignment PIN_105 -to Expander_MX_DR
set_location_assignment PIN_100 -to Lite_21
set_location_assignment PIN_38 -to Lite_31
set_location_assignment PIN_87 -to Lite_32
set_location_assignment PIN_83 -to Lite_34
set_location_assignment PIN_42 -to Lite_38
set_location_assignment PIN_67 -to Lite_41
set_location_assignment PIN_73 -to Lite_42
set_location_assignment PIN_65 -to Lite_44
set_location_assignment PIN_60 -to Lite_48
set_location_assignment PIN_55 -to Lite_51
set_location_assignment PIN_69 -to Lite_52
set_location_assignment PIN_58 -to Lite_54
set_location_assignment PIN_71 -to Lite_58
set_location_assignment PIN_101 -to Lite_Double_Bonus
set_location_assignment PIN_106 -to Lite_Extra_Ball
set_location_assignment PIN_84 -to Lite_Special
set_location_assignment PIN_49 -to MISO_SDCard
set_location_assignment PIN_44 -to MOSI_SDCard
set_location_assignment PIN_85 -to Play_Signal
set_location_assignment PIN_103 -to Rejector_Control
set_location_assignment PIN_144 -to reset_sw
set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to reset_sw
set_location_assignment PIN_46 -to SPI_CLK_SDCard
set_location_assignment PIN_34 -to USB_Rx
set_location_assignment PIN_22 -to USB_Tx
set_location_assignment PIN_89 -to DIA[1]
set_location_assignment PIN_90 -to DIA[2]
set_location_assignment PIN_91 -to DIA[3]
set_location_assignment PIN_113 -to DOA[1]
set_location_assignment PIN_112 -to DOA[2]
set_location_assignment PIN_115 -to DOA[3]
set_location_assignment PIN_125 -to Disp_DA[0]
set_location_assignment PIN_126 -to Disp_DB[0]
set_location_assignment PIN_68 -to Bonus[0]
set_location_assignment PIN_111 -to DOA[0]
set_location_assignment PIN_24 -to S3
set_location_assignment PIN_25 -to S6
set_location_assignment PIN_88 -to DIA[0]
set_location_assignment PIN_1 -to I_LED1_SD
set_location_assignment PIN_3 -to I_LED2_D1
set_location_assignment PIN_10 -to I_LED3_D2
set_location_assignment PIN_31 -to Audio_RX
set_location_assignment PIN_7 -to music
set_location_assignment PIN_32 -to sound
set_location_assignment PIN_51 -to SPI_CLK_EEPROM
set_location_assignment PIN_50 -to MOSI_EEPROM
set_location_assignment PIN_53 -to MISO_EEPROM
set_location_assignment PIN_52 -to CS_EEPROM
